#!/usr/bin/env node
/**
 * Generates src/generated/models.ts from openapi.json.
 * Produces a TypeScript class for each entry in components.schemas.
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const spec = JSON.parse(readFileSync(resolve(root, "openapi.json"), "utf-8"));
const schemas = spec?.components?.schemas ?? {};

/** Map an OpenAPI schema node to a TypeScript type string. */
function toTsType(schema, allSchemaNames) {
  if (!schema) return "unknown";

  if (schema.$ref) {
    const name = schema.$ref.split("/").pop();
    return name;
  }

  if (schema.type === "array") {
    const itemType = toTsType(schema.items, allSchemaNames);
    return `${itemType}[]`;
  }

  if (schema.enum) {
    return schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  }

  switch (schema.type) {
    case "integer":
      return "number";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "string":
      return "string";
    case "object":
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

const allSchemaNames = Object.keys(schemas);
const lines = [
  "// Auto-generated by scripts/generate-classes.mjs — do not edit manually.",
  "// Run `npm run generate:openapi` to regenerate.",
  "",
];

for (const [name, schema] of Object.entries(schemas)) {
  lines.push(`export class ${name} {`);

  const properties = schema.properties ?? {};
  for (const [propName, propSchema] of Object.entries(properties)) {
    const tsType = toTsType(propSchema, allSchemaNames);
    lines.push(`  ${propName}?: ${tsType};`);
  }

  if (Object.keys(properties).length > 0) lines.push("");

  lines.push(`  constructor(data?: Partial<${name}>) {`);
  lines.push("    if (data) Object.assign(this, data);");
  lines.push("  }");
  lines.push("}");
  lines.push("");
}

const outPath = resolve(root, "src/generated/models.ts");
writeFileSync(outPath, lines.join("\n"), "utf-8");
console.log(`Generated ${outPath}`);
